### ISSUE TITLE
Controller does not exist error

### ISSUE THREAD

**Issue by adetoola** [todstoychev/Laravel5Starter#11]
Hi,
I created a controller but getting the following error.

ReflectionException in ControllerInspector.php line 32:
Class App\Http\Controllers\StaticPagesController@faq does not exist

i have tried 
php artisan acl:update,
composer dump-autoload to no avail. 
How do i resolve this issue? Thanks

**Comment by todstoychev** [comment]
Hi thanx for the response this is a bug I think. I will got to resolve 
this. I will got to investigate this.

**Comment by todstoychev** [comment]
I think I found your issue. The problem is in the name of the file that holds the controller. Every controller in Laravel is usually declared as MyControllerNameController. You got to name your file StaticPagesController. Your class also got to have the same name. In the routes.php you got have something similar to `Route::controller('static-pages', 'StaticPagesController');` or maybe `Route::get('faq', 'StaticPagesController@getFaq');`. Put every new controller routing at the top of the Public user routes block. Then running the `php artisan acl:update` should return you the name of the new controller@action added to the ACL. Example:

```
    $ php artisan acl:update

    Added App\Http\Controllers\StaticPagesController@getFaq

    Done. 

```

You got to be able to see your new routes at the admin panel's section - Permissions. All new routes are with public access by default.
Hope this helps you.

**Comment by todstoychev** [comment]
BTW I was planing add a module for static pages but I will see. Now I am concentrated on other tasks.
