### ISSUE TITLE
Why editing roles add a new role?

### ISSUE THREAD

**Issue by gwilliamsontsb** [todstoychev/Laravel5Starter#2]
When I am editing a role it add a new role instead. Views/admin/roles/add_form.blade.php has:

@if (isset($user))
form action=edit
@else
form action=add

**Comment by todstoychev** [comment]
Thanx I will check it. Maybe it is something that I had missed.

**Comment by todstoychev** [comment]
Yes it is my fault and this is a bug that I had missed. Everything is fixed now I think.

**Comment by todstoychev** [comment]
Thanx for the report. If you catch somethig else please write and I will fix it

**Comment by gwilliamsontsb** [comment]
I has been trying to fix something else but I was wondering if you came with a solution already. When you edit a role (after fixing the bug described above) I you hit save without changing the name of the role it generates the error: The role has already been taken. Seems like the reason is the unique rule in App\Http\Requests\Request\EditRoleRequest. I added a list of permissions which can be attached to every role but I am not able to save because the unique rule.

![role already taken](https://cloud.githubusercontent.com/assets/12038948/7536388/7352b3b6-f55d-11e4-9d08-49a3a1b9869c.PNG)

**Comment by gwilliamsontsb** [comment]
I figure out this way... may not be the most elegant:

```
public function rules() {
    $some =$this->all();
    if(array_key_exists('role_id', $some))
        $fix_unique_role = ',id,'.$some['role_id'];
    else
        $fix_unique_role = '';
    return [
        'role' => 'required|alpha|unique:roles'.$fix_unique_role
    ];
}
```

#role_id is included has a hidden field in the form @if (isset($role))

**Comment by todstoychev** [comment]
Aham so you need to remove the unique permission but also I will have to think of something. This will take me some time. By the way your idea is not bad. The reason is not only the unique rule in the request. There is also unique attribute in the migration, attached to the column. I will got to think for a way to check if the role exists already, when you are adding a new one. This will keep the user from adding 2 roles with the same names. Thanks for the response. I will take measures to edit the application.

**Comment by todstoychev** [comment]
I had fixed the things. Try now it got to run as you expected. You will need to rerun the migrations because there are some changes there.

**Comment by gwilliamsontsb** [comment]
Todor, thanks a lot for your responses. Were very helpful. I am working
with your program for learning purposes. I added a permissions model where
a role may have many permissions (Permission examples: updateCustomer,
addOrder, deleteInvoice, menuEquipment...).

You have hasRole as a method in class Auth. What will be the best approach
to add the method hasPermission in Auth class without breaking Laravel
rules? Or what will be your best suggestion to do it? I will like to be
able to do Auth::hasPermission('menuEquipment') in a view.

**Comment by todstoychev** [comment]
If the permissions are related to the roles, you can get them via the User class instance. The `roles` attribute of the User class returns array. This is because you can have several roles for a an user. Maybe the right way is to check to which role is assigned the permission and then check if the user has this role. You can use the method from the User class - hasRole(). The best place to create such a method for me is the Permissions model. You got to have such a model I think. Write a method there that gets the roles to which the permission is attached and then check if the user has one of the roles. If we suggest that the Permission and Role models has a relation the code got look like:

```
public static function getRolesAssigned($permission_id) {
    $query = self::select('role_name')->where('id', $permission_id)->get();

    // You can use to array probaly
    return $query->toArray();
}
```

Then you can create a method in the User method to control the permissions:

```
public static function checkPermission($permission_id) {
    $roles_to_permission = Permission::getRolesAssigned($permission_id);

    foreach ($roles_to_permission as $role) {
        if (self::hasRole($role)) {
            return true;
        }
    }

    return false;
}
```

If the user has the role attached to the permission the loop will exit with true, else the loop will cycle to the end and the false will be returned.

**Comment by gwilliamsontsb** [comment]
Will be a way to make it start in english? I changed the fallback_locale to
EN but it do not work. It always try to start in BG.

**Comment by todstoychev** [comment]
I will see it.

**Comment by todstoychev** [comment]
Your problem may come from the session. There is a middleware named Locale which is responsible for checking and using locale. So when you choose a locale from the menu it is recorded in a session variable named 'locale'. The middleware checks if there is such variable set,  the logic sets it as an application locale. If there is no variable named 'locale' in the session then the fallback locale setted in the settings section is used as application locale. This logic overrides the original behavior of Laravel, where the locale and fallback locale are set in the configuration files.
My advice is to check `config/session.php` and set the session driver to file:

```
'driver' => env('SESSION_DRIVER', 'file'),
```

If it set check the permissions. Is the application has right to write in the `storage/framework/sessions`. But if there is such case you got get errors.

**Comment by gwilliamsontsb** [comment]
That works fine. If I choose EN or other language will store in the
sessions file storage/framework/sessions correctly and the session variable
locale is changed to EN correctly and all day you will have EN language.
But next day when you open your browser, or when the session is expired if
you go to the application will create a new session with locale = BG. Even
my config and settings are:

settings table:
1localesen, bg2sitename_enMy site3sitename_bgМоят сайт4fallback_localeen5
faviconfavicon.ico

my config\app.php has:
'locale' => 'en',
'fallback_locale' => 'en',

this is the content of my session:

a:6:{s:6:"_token";s:40:"3Rj1WrEX8mnO1cfZVHjuiB86ZtVh119oeXRHvuKO";
s:6:"locale";s:2:"bg";s:22:"PHPDEBUGBAR_STACK_DATA";a:0:{}
s:9:"_previous";a:1:{s:3:"url";s:21:"http://localhost:8000";}
s:9:"_sf2_meta";a:3:{s:1:"u";i:1432306462;s:1:"c";i:1432306462;
s:1:"l";s:1:"0";}s:5:"flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}

**Comment by todstoychev** [comment]
Did you change you fallback locale from the settings in the admin panel. 
Because this the place from where the fallback locale is taken. It 
overrides the config file.

**Comment by gwilliamsontsb** [comment]
Excelent! It worked now! Thanks.
