### ISSUE TITLE
db seed error

### ISSUE THREAD

**Issue by mohd-aidi** [todstoychev/Laravel5Starter#31]
Hi, i have this issue came up when i run php artisan db:seed

[InvalidArgumentException]
  The class 'App\Models\Product' must be inherited from 'Illuminate\Database\Eloqu
  ent\Model'.

and i tries to find the product model but not found in the directory mentioned above.

**Comment by todstoychev** [comment]
It is an result of my previous error. I made a commit to the wrong repo before few days. I think i fixed that. But seems like there is problem. I will see it in next few days.

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.4.40&pv=4.4.4&source=email_footer_2] On Thu, Jun 16, 2016 at 4:39 AM, mohd-aidi < notifications@github.com [notifications@github.com] > wrote:
Hi, i have this issue came up when i run php artisan db:seed

[InvalidArgumentException]
The class 'App\Models\Product' must be inherited from 'Illuminate\Database\Eloqu
ent\Model'.

and i tries to find the product model but not found in the directory mentioned above.

**Comment by todstoychev** [comment]
OK I just fixed it. Check out 0.9.6 release. It should do the trick. The problem was caused from a some things leaved after I've commited data in this repo from another one which was based on it. Shit happens sometimes ;) you know. Thanks for the reported problem and cheers!

**Comment by mohd-aidi** [comment]
sorry for the late reply..i will check out latest version..thank you for the fixed.. :)
